name: arduino

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # We use the `arduino/setup-arduino-cli` action to install and
    # configure the Arduino CLI on the system.
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1.0.0

    # We then install the platform, which one will be determined
    # dynamically by the build matrix.
    - name: Install platform
      run: |
        printf "board_manager:\n  additional_urls:\n    - https://dl.espressif.com/dl/package_esp32_index.json\n" > cli-config.yml
        arduino-cli core update-index --config-file cli-config.yml
        arduino-cli core install esp32:esp32 --config-file cli-config.yml
        arduino-cli lib install "Adafruit BME280 Library"

    # Finally, we compile the sketch, using the FQBN that was set
    # in the build matrix.
    - name: Compile Sketch
      run: arduino-cli compile --fqbn esp32:esp32:esp32 --verbose siton-wifi.cpp
